export ZSH="$HOME/.oh-my-zsh"
export UPDATE_ZSH_DAYS=7

# ZSH_THEME="sung"
ZSH_THEME="agnoster"
ENABLE_CORRECTION="true"
DEFAULT_USER=$USER

plugins=(
  git
  docker
  yarn
)

source $ZSH/oh-my-zsh.sh

#archey -o
archey

#-------------------
# Personal Aliases
#-------------------
alias rm='rm -i'
alias cp='cp -i'
alias mv='mv -i'
alias cls='clear'
alias mkdir='mkdir -p'

alias h='history'
alias j='jobs -l'
alias which='type -a'

alias path='echo -e ${PATH//:/\\n}'
alias libpath='echo -e ${LD_LIBRARY_PATH//:/\\n}'

alias du='du -kh'    # Makes a more readable output.
alias df='sudo df -kh'

# alias ll='ls -FGlAhp'
alias lm='ll |more'        #  Pipe through 'more'
alias lr='ll -R'           #  Recursive ls.
alias la='ll -A'           #  Show hidden files.
alias tree='tree -Csuh'    #  Nice alternative to 'recursive ls' ...

alias desk='cd ~/Desktop'
alias godev='cd ~/Development/'
alias dev='~/Development'

export NVM_DIR="$HOME/.nvm"
[ -s "/usr/local/opt/nvm/nvm.sh" ] && . "/usr/local/opt/nvm/nvm.sh"
[ -s "/usr/local/opt/nvm/etc/bash_completion.d/nvm" ] && . "/usr/local/opt/nvm/etc/bash_completion.d/nvm"

# SDK MAN
# source "$HOME/.sdkman/bin/sdkman-init.sh"

# Docker
alias dk='docker'
alias dkc='docker-compose'
source <(kubectl completion zsh)
export PATH="/usr/local/opt/curl/bin:$PATH"
# export PATH="/usr/local/opt/mysql-client/bin:$PATH"

# GO LANG
export GOROOT=/usr/local/var/homebrew/linked/go/libexec
export GOPATH=$HOME/Development/go
export PATH="$PATH:$GOPATH/bin"
# export PATH="/usr/local/opt/gnu-tar/libexec/gnubin:$PATH"

# HYPERLEDGER FABRIC
# export FABRIC_HOME=$GOPATH/src/github.com/hyperledger/fabric
# export PATH=$PATH:$GOPATH/src/github.com/hyperledger/fabric/.build/bin

# CUSTOM SETTINGS
source /usr/local/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
source /usr/local/share/zsh-autosuggestions/zsh-autosuggestions.zsh

# # INDY-SDK
# export DYLD_LIBRARY_PATH=/Users/sung/Development/10.nuritelecom/indy-sdk/libindy/target/debug
# export LD_LIBRARY_PATH=/Users/sung/Development/10.nuritelecom/indy-sdk/libindy/target/debug
# # INDY-CLI
# export PATH=$PATH:/Users/sung/Development/10.nuritelecom/indy-lib/bin

# pyenv & pyenv-virtualenv
export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init --path)"
eval "$(pyenv init -)"

# GVM for golang version manager
# [[ -s "/Users/sung/.gvm/scripts/gvm" ]] && source "/Users/sung/.gvm/scripts/gvm"
